#!name=iOS Location Spoofer Nightmarket Server
#!desc=Chặn các tọa độ GPS do máy chủ định vị của Apple trả về và thay thế chúng bằng một vị trí tùy chỉnh. Hoạt động với Shadowrocket/Surge.
#!version=1

[Script]
iOS Location Spoofer = type=http-response,pattern=^https?:\/\/(?:gs-loc(?:-cn)?\.apple\.com|bluedot\.is\.autonavi\.com(?:\.gds\.alibabadns\.com)?)\/clls\/wloc(?:\?.*)?$,requires-body=1,binary-body-mode=1,max-size=1048576,timeout=10,script-path=https://raw.githubusercontent.com/mekos2772/ios-location-spoofer/main/location-spoofer.js,argument=mode=response&latitude=37.3349&longitude=-122.00902&horizontalAccuracy=39&verticalAccuracy=1000&altitude=530&debug=false

[MITM]
hostname = %APPEND% gs-loc.apple.com, gs-loc-cn.apple.com, bluedot.is.autonavi.com, bluedot.is.autonavi.com.gds.alibabadns.com

# -----------------------------
# Author
# -----------------------------
# 👤 Author: mekos2772 - NightmarketServer
# 💬 Discord: https://discord.gg/juY9tw5AJY
